// <auto-generated />
using System;
using Ecommerce.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ecommerce.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251223025906_AddInitialEntities")]
    partial class AddInitialEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.API.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCliente"));

                    b.Property<DateTime?>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<Guid>("IdPersona")
                        .HasColumnType("uuid")
                        .HasColumnName("id_persona");

                    b.Property<Guid>("PersonaIdPersona")
                        .HasColumnType("uuid");

                    b.Property<int>("Puntos")
                        .HasColumnType("integer")
                        .HasColumnName("puntos");

                    b.HasKey("IdCliente");

                    b.HasIndex("PersonaIdPersona");

                    b.ToTable("cliente");
                });

            modelBuilder.Entity("Ecommerce.API.Models.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_empleado");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEmpleado"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ingreso");

                    b.Property<Guid>("IdPersona")
                        .HasColumnType("uuid")
                        .HasColumnName("id_persona");

                    b.Property<Guid>("PersonaIdPersona")
                        .HasColumnType("uuid");

                    b.HasKey("IdEmpleado");

                    b.HasIndex("PersonaIdPersona");

                    b.ToTable("empleado");
                });

            modelBuilder.Entity("Ecommerce.API.Models.Persona", b =>
                {
                    b.Property<Guid>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id_persona");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("primer_apellido");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("primer_nombre");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("segundo_apellido");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("segundo_nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdPersona");

                    b.ToTable("persona");
                });

            modelBuilder.Entity("Ecommerce.API.Models.PersonaRol", b =>
                {
                    b.Property<Guid>("IdPersona")
                        .HasColumnType("uuid")
                        .HasColumnName("id_persona");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    b.Property<Guid>("PersonaIdPersona")
                        .HasColumnType("uuid");

                    b.Property<int>("RolIdRol")
                        .HasColumnType("integer");

                    b.HasKey("IdPersona", "IdRol");

                    b.HasIndex("PersonaIdPersona");

                    b.HasIndex("RolIdRol");

                    b.ToTable("persona_rol");
                });

            modelBuilder.Entity("Ecommerce.API.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProducto"));

                    b.Property<int>("Existencias")
                        .HasColumnType("integer");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("IdProducto");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("Ecommerce.API.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdRol");

                    b.ToTable("rol");
                });

            modelBuilder.Entity("Ecommerce.API.Models.Salario", b =>
                {
                    b.Property<int>("IdSalario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_salario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSalario"));

                    b.Property<int>("EmpleadoIdEmpleado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("id_empleado");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric")
                        .HasColumnName("monto");

                    b.HasKey("IdSalario");

                    b.HasIndex("EmpleadoIdEmpleado");

                    b.ToTable("salario");
                });

            modelBuilder.Entity("Ecommerce.API.Models.Cliente", b =>
                {
                    b.HasOne("Ecommerce.API.Models.Persona", "Persona")
                        .WithMany("Clientes")
                        .HasForeignKey("PersonaIdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Ecommerce.API.Models.Empleado", b =>
                {
                    b.HasOne("Ecommerce.API.Models.Persona", "Persona")
                        .WithMany("Empleados")
                        .HasForeignKey("PersonaIdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Ecommerce.API.Models.PersonaRol", b =>
                {
                    b.HasOne("Ecommerce.API.Models.Persona", "Persona")
                        .WithMany("PersonaRoles")
                        .HasForeignKey("PersonaIdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.API.Models.Rol", "Rol")
                        .WithMany("PersonaRoles")
                        .HasForeignKey("RolIdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Ecommerce.API.Models.Salario", b =>
                {
                    b.HasOne("Ecommerce.API.Models.Empleado", "Empleado")
                        .WithMany("Salarios")
                        .HasForeignKey("EmpleadoIdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("Ecommerce.API.Models.Empleado", b =>
                {
                    b.Navigation("Salarios");
                });

            modelBuilder.Entity("Ecommerce.API.Models.Persona", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Empleados");

                    b.Navigation("PersonaRoles");
                });

            modelBuilder.Entity("Ecommerce.API.Models.Rol", b =>
                {
                    b.Navigation("PersonaRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
